version: '3.8'

services:
    backend: 
        container_name: api-laravel_DC
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment: 
            DB_HOST: db
            DB_CHALLENGE: db_challenge
            DB_USERNAME: root
            DB_PASSWORD: root
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app/backend
        depends_on: 
            - db
        networks:
            - app

    frontend:
        container_name: app-react_DC
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app/frontend
        depends_on:
            - backend
        networks:
            - app

    db:
        container_name: srv-mysql_DC
        image: mysql:8.0.30
        
        restart: always
        environment:
            MYSQL_DATABASE: 'db_challenge'
            # MYSQL_USER: 'root'
            # MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
          - "./db/mysql/data:/var/lib/mysql"
          - "./db/mysql/initdb.d:/docker-entrypoint-initdb.d"
        networks:
            - app
networks:
    app:
        driver: bridge
