version: '3.7'

services:
    backend: 
        container_name: api-laravel_C
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment: 
            DB_HOST: db
            DB_CHALLENGE: db_challenge
            DB_USERNAME: root
            DB_PASSWORD: root
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app/backend
        depends_on: 
            - db
        networks:
            - app

    frontend:
        container_name: app-react_C
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        stdin_open: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app/frontend
        depends_on:
            - backend
        networks:
            - app

    db:
        container_name: srv-mysql_C
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'db_challenge'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
          - .dbdata:/var/lib/mysql/
        networks:
            - app


networks:
    app:
        driver: bridge